clean-up dirs rewrite version bump

diff --git a/content/usr/share/usbmount/usbmount b/content/usr/share/usbmount/usbmount
--- a/content/usr/share/usbmount/usbmount
+++ b/content/usr/share/usbmount/usbmount
@@ -204,9 +204,14 @@ if [ "$ACTION" = add ]; then
 	    fi
 	fi
     fi
-    # check whether this was mounted before under different dir
-    prevdir=$(grep $DEVNAME /var/run/usbmount/proc-mounts | awk '{print $2}')
-    [ -n "$prevdir" ] && [ -e "/var/run/usbmount/$(basename $prevdir)" ] && [ "/media/$mountpoint$counter" != "$prevdir" ] && rmdir "$prevdir" || true
+    log info "cleaning up mnt dirs"
+    # clean up old not deleted dirs (not fixed mountpoints defined in /etc/fstab)
+    fstabdirs=$(while read dev mntdir stuff; do test -n "$mntdir" && test "$(dirname $mntdir)" = "/media" && printf "%s\n" $mntdir ; done < /etc/fstab; true)
+    for d in $(ls /media); do
+	if ! in_list "/media/$d" "$fstabdirs"; then
+	    mountpoint -q /media/$d || rmdir /media/$d
+	fi
+    done
     # do a copy of /proc/mounts
     cat /proc/mounts > /var/run/usbmount/proc-mounts
 
