1.0-0.4 bringing bg launching (async)

diff --git a/content/etc/usbmount/mount.d/symlink-to-usb b/content/etc/usbmount/mount.d/symlink-to-usb
--- a/content/etc/usbmount/mount.d/symlink-to-usb
+++ b/content/etc/usbmount/mount.d/symlink-to-usb
@@ -1,9 +1,47 @@
 #!/bin/sh
 
-/etc/usbmount/umount.d/symlink-to-usb
+# Test if the first parameter is in the list given by the second
+# parameter.
+in_list()
+{
+    for v in $2; do
+        [ "$1" != "$v" ] || return 0
+    done
+    return 1
+}
+
+# clean up old not deleted dirs (not fixed mountpoints defined in /etc/fstab)
+fstabdirs=$(while read dev mntdir stuff; do test -n "$mntdir" && test "$(dirname $mntdir)" = "/media" && printf "%s\n" $mntdir ; done < /etc/fstab; true)
+for d in $(find  /media  -maxdepth 1 -type d); do
+    test $d = /media && continue
+    if ! in_list "$d" "$fstabdirs"; then
+	mountpoint -q $d || rmdir $d
+    fi
+done
+
+#clean up symlinks
+for f in $(find  /media  -maxdepth 1 -type d); do 
+    keep_first=1
+    for g in $(find  /media  -maxdepth 1 -type l ); do
+	if [ "$(readlink -e $g)" = "$f" ]; then
+	    if [ $keep_first -eq 1 ]; then
+	        keep_first=0
+	        continue
+	    fi
+	    rm "$g"
+	fi
+    done
+done
+
+for g in $(find  /media  -maxdepth 1 -type l ); do
+    [ ! -e "$(readlink -e $g)" ] && rm "$g"
+done
+
+#do the actual stuff we wanted
+test -z "$UM_MOUNTPOINT" && exit 0
 
 counter=0
-while test -e /media/usb$counter; do counter=$(($counter + 1)); done
+while test -h /media/usb$counter; do counter=$(($counter + 1)); done
 
 ln -s /media/$UM_MOUNTPOINT /media/usb$counter || exit 1
 
